Website = "https://github.com/aixoio/aixoio-privacy-tools"

[Details]
  Icon = "Icon.png"
  Name = "aixoio's privacy tools"
  ID = "com.github.aixoio.aixoio-privacy-tools"
  Version = "2.1.0"
  Build = 29
