Website = "https://github.com/aixoio/aixoio-privacy-tools"

[Details]
  Icon = "Icon.png"
  Name = "aixoio's privacy tools"
  ID = "com.github.aixoio.aixoio-privacy-tools"
  Version = "0.0.1"
  Build = 4

[LinuxAndBSD]
  GenericName = "aixoio's privacy tools"
  Categories = ["Utility"]
  Comment = "A collection of privacy tools"
  Keywords = ["aixoio", "tools", "privacy", "tool", "encryption", "security", "privacy", "privacy tools", "aixoio privacy tools"]
